apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prometheus-thanos.fullname" . }}-store-gateway
  labels:
    app.kubernetes.io/name: {{ include "prometheus-thanos.name" . }}-store-gateway
    helm.sh/chart: {{ include "prometheus-thanos.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.storeGateway.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "prometheus-thanos.name" . }}-store-gateway
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "prometheus-thanos.name" . }}-store-gateway
        app.kubernetes.io/instance: {{ .Release.Name }}
        prometheus-thanos-peer: "true"
    spec:
      containers:
        - name: {{ .Chart.Name }}-store-gateway
          imagePullPolicy: {{ .Values.storeGateway.image.pullPolicy }}
          image: "{{ .Values.storeGateway.image.repository }}:{{ .Values.storeGateway.image.tag }}"
          args:
          - store
          - --data-dir=/data
          - --log.level={{ .Values.storeGateway.logLevel }}
          {{- if .Values.cluster.enabled }}          
          - --cluster.address={{ .Values.cluster.address }}:{{ .Values.cluster.port}}
          - --cluster.peers={{ include "prometheus-thanos.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.cluster.port }}          
          {{- else }}
          - --cluster.disable
          {{- end }}
          - --index-cache-size={{ .Values.storeGateway.indexCacheSize }}
          - --chunk-pool-size={{ .Values.storeGateway.chunkPoolSize }}
          {{- range $key, $value := .Values.storeGateway.additionalFlags }}
          - --{{ $key }}{{if $value }}={{ $value }}{{end}}
          {{- end }}
          {{- if .Values.storeGateway.objStoreType }}
          - |
            --objstore.config=type: {{ .Values.storeGateway.objStoreType }} 
            config:
            {{- toYaml .Values.storeGateway.objStoreConfig | nindent 14 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 10902
              protocol: TCP
            - name: grpc
              containerPort: 10901
              protocol: TCP
            - name: cluster
              containerPort: {{ .Values.cluster.port }}
              protocol: TCP
          {{- if .Values.storeGateway.extraEnv }}
          env:
            {{- toYaml .Values.storeGateway.extraEnv | nindent 12 }}  
          {{- end }}
          livenessProbe:
            httpGet:
              path: /metrics
              port: http
            initialDelaySeconds: {{ .Values.storeGateway.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.storeGateway.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.storeGateway.livenessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.storeGateway.livenessProbe.timeoutSeconds }}
          readinessProbe:
            httpGet:
              path: /metrics
              port: http
            initialDelaySeconds: {{ .Values.storeGateway.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.storeGateway.readinessProbe.periodSeconds }}
            successThreshold: {{ .Values.storeGateway.readinessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.storeGateway.readinessProbe.timeoutSeconds }}
          resources:
            {{- toYaml .Values.storeGateway.resources | nindent 12 }}
          {{- with .Values.storeGateway.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 14 }}
          {{- end }}
      {{- with .Values.storeGateway.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.storeGateway.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.storeGateway.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.storeGateway.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
    {{- end }}

