apiVersion: v1
version: 0.3.0
appVersion: 1.7.10
name: influxdb-backup
description: InfluxDB backup Helm chart for Kubernetes
home: https://www.influxdata.com
sources:
  - https://github.com/kiwigrid/helm-charts
  - https://github.com/influxdata/influxdb
icon: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Influxdb_logo.svg/512px-Influxdb_logo.svg.png
maintainers:
- name: monotek
  email: andre.bauer@kiwigrid.com
