apiVersion: v1
appVersion: "1.0.0-M3"
description: A Helm chart for Eclipse Ditto
name: ditto-digital-twins
version: 0.7.1
home: www.eclipse.org/ditto
sources:
- https://github.com/eclipse/ditto
- https://github.com/kiwigrid/helm-charts/tree/master/charts/ditto-digital-twins
icon: https://www.eclipse.org/ditto/images/ditto.svg
deprecated: true
