apiVersion: v1
kind: Secret
metadata:
  name: {{ include "influxdb-backup.fullname" . }}
  labels:
    {{- include "influxdb-backup.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $instances := .Values.backup.instances }}
  {{ if $instances.existingSecret }}
  {{ $instances.name }}-admin-password: {{ $instances.pass | b64enc | quote }}
  {{- end }}  
  {{- end }}
  {{- if and (.Values.backup.uploadProviders.google.enabled) (not .Values.backup.uploadProviders.google.existingSecret) -}}
  {{ .Values.backup.uploadProviders.google.secretKey }}: {{ .Values.backup.uploadProviders.google.secret | b64enc | quote }}
  {{- end }}
  {{ if and (.Values.backup.uploadProviders.azure.enabled) (not .Values.backup.uploadProviders.azure.existingSecret) -}}
  {{ .Values.backup.uploadProviders.azure.secretKey }}: {{ .Values.backup.uploadProviders.azure.secret | b64enc | quote }}
  {{- end }}
