apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  labels:
{{ include "enmasse.labels" . | indent 4 }}
  name: v1alpha1.user.enmasse.io
spec:
  group: user.enmasse.io
  groupPriorityMinimum: 1000
  insecureSkipTLSVerify: true
  service:
    name: {{ include "enmasse.fullname" . }}-api-server
    namespace: {{.Release.Namespace}}
  version: v1alpha1
  versionPriority: 15
