apiVersion: v1
appVersion: "2.1.3.RELEASE"
description: A Helm chart for Spring Cloud Config Server
name: spring-cloud-config-server
version: 0.1.0
home: https://github.com/hyness/spring-cloud-config-server
sources:
- https://github.com/hyness/spring-cloud-config-server
- https://github.com/kiwigrid/helm-charts/tree/master/charts/spring-cloud-config-server
maintainers:
- name: rpahli
  email: rico.pahlisch@kiwigrid.com
