apiVersion: v1
appVersion: "1.2"
description: A Helm chart for Kubernetes Policy Controller and the open policy agent to manage your cluster policies
name: kubernetes-policy-controller
version: 0.1.1
home: https://github.com/kiwigrid/helm-charts
icon: https://www.openpolicyagent.org/img/opa-logo.svg
sources:
- https://github.com/open-policy-agent/kubernetes-policy-controller
- https://github.com/open-policy-agent/opa
maintainers:
- name: rpahli
  email: rico.pahlisch@kiwigrid.com
