{{- if .Values.podSecurityPolicy.enabled }}
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ template "fluentd-elasticsearch.fullname" . }}
  labels:
{{ include "fluentd-elasticsearch.labels" . | indent 4 }}
    {{- if semverCompare "> 1.6" .Capabilities.KubeVersion.GitVersion }}
    kubernetes.io/cluster-service: "true"
    {{- end }}
    addonmanager.kubernetes.io/mode: Reconcile
  annotations:
{{- if .Values.podSecurityPolicy.annotations }}
{{ toYaml .Values.podSecurityPolicy.annotations | indent 4 }}
{{- end }}
spec:
  privileged: false
  allowPrivilegeEscalation: true
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'hostPath'
    - 'secret'
  allowedHostPaths:
    - pathPrefix: {{ .Values.hostLogDir.varLog}}
      readOnly: false
    - pathPrefix: {{ .Values.hostLogDir.dockerContainers}}
      readOnly: true
    - pathPrefix: {{ .Values.hostLogDir.libSystemdDir}}
      readOnly: true
  hostNetwork: false
  hostPID: false
  hostIPC: false
  runAsUser:
    rule: 'RunAsAny'
  runAsGroup:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  readOnlyRootFilesystem: false
  hostPorts:
    - min: 1
      max: 65535
{{- end }}
