apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes error pages for traefik
name: error-pages
version: 0.1.2
home: https://github.com/kiwigrid/helm-charts
sources:
- https://github.com/kiwigrid/helm-charts
maintainers:
- name: rpahli
  email: rico.pahlisch@kiwigrid.com
