apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spring-cloud-config-server.fullname" . }}
  labels:
    {{- include "spring-cloud-config-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "spring-cloud-config-server.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "spring-cloud-config-server.labels" . | nindent 8 }}
        {{- with .Values.podTemplate.annotations }}  
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if .Values.secrets.githubPrivateKey }}
      volumes:
        - name: {{ include "spring-cloud-config-server.fullname" . }}-githubprivatekey
          secret:
            secretName: {{ include "spring-cloud-config-server.fullname" . }}-githubprivatekey
            defaultMode: 0600
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.secrets.githubPrivateKey }}
          volumeMounts:
            - name: {{ include "spring-cloud-config-server.fullname" . }}-githubprivatekey
              readOnly: true
              mountPath: "/root/.ssh/"
          {{- end }}
          ports:
            - name: http
              containerPort: 8888
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
          env:
          {{- if .Values.config.gitUri }}
          - name: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
            value: "{{ .Values.config.gitUri }}"
          {{- else }}
          - name: SPRING_PROFILES_ACTIVE
            value: "native"
          {{- end}}
          - name: SPRING_CLOUD_CONFIG_SERVER_GIT_SEARCHPATHS
            value: "{{ .Values.config.gitSearchpath }}"
          - name: SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME
            valueFrom:
              secretKeyRef:
                name: "{{ include "spring-cloud-config-server.fullname" . }}"
                key: "gitUsername"
          - name: SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "{{ include "spring-cloud-config-server.fullname" . }}"
                key: "gitPassword"
          {{- if .Values.extraEnv }}
            {{- toYaml .Values.extraEnv | nindent 10 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
