apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "spring-cloud-config-server.fullname" . }}
  labels:
{{ include "spring-cloud-config-server.labels" . | indent 4 }}
data:
  {{- if .Values.secrets.gitUsername }}
  gitUsername: {{ .Values.secrets.gitUsername | b64enc | quote }}
  {{- else }}
  gitUsername: {{ randAlphaNum 20 | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.gitPassword }}
  gitPassword: {{ .Values.secrets.gitPassword | b64enc | quote }}
  {{- else }}
  gitPassword: {{ randAlphaNum 20 | b64enc | quote }}
  {{- end }}
---
{{- if .Values.secrets.githubPrivateKey }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "spring-cloud-config-server.fullname" . }}-githubprivatekey
  labels:
{{ include "spring-cloud-config-server.labels" . | indent 4 }}
data:
  id_rsa: {{ .Values.secrets.githubPrivateKey }}
  known_hosts: {{ .Values.secrets.githubKnownHosts }}
{{- end }}
